-- CREATE SCHEMA `footfalltrackerboot` ;



CREATE TABLE GYMS
(
	GYM_ID VARCHAR(50) NOT NULL PRIMARY KEY,
	GYM_NAME VARCHAR(200) NOT NULL,
	AUTH_METHOD VARCHAR(100),
	PASSWD VARCHAR(200)
);

CREATE TABLE GYM_MEMBERS
(
	MEMBER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
	MEMBER_NAME VARCHAR(200) NOT NULL,
	GYM_ID VARCHAR(50) NOT NULL,
	ENCODINGS JSON,
	FOREIGN KEY (GYM_ID) REFERENCES GYMS(GYM_ID),
);

CREATE TABLE FOOTFALL
(
	FOOTFALL_ID VARCHAR(50) NOT NULL PRIMARY KEY,
	MEMBER_ID VARCHAR(50) NOT NULL UNIQUE,
	GYM_ID VARCHAR(50) NOT NULL,
	FOOTFALL_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ENTRY_EXIT VARCHAR(10),
	X_COORD_FRAC FLOAT,
	Y_COORD_FRAC FLOAT,
	UNIQUE (MEMBER_ID, GYM_ID,FOOTFALL_TIMESTAMP),
	FOREIGN KEY (MEMBER_ID) REFERENCES GYM_MEMBERS(MEMBER_ID),
	FOREIGN KEY (GYM_ID) REFERENCES GYMS(GYM_ID),
);


CREATE TABLE MEMBER_SESSIONS
(
	MEMBER_SESSION_ID VARCAHR(50) NOT NULL PRIMARY KEY,
	MEMBER_ID VARCHAR(50) NOT NULL,
	GYM_ID VARCHAR(50) NOT NULL,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	UNIQUE (MEMBER_ID, GYM_ID,FOOTFALL_TIMESTAMP),
	FOREIGN KEY (MEMBER_ID) REFERENCES GYM_MEMBERS(MEMBER_ID),
	FOREIGN KEY (GYM_ID) REFERENCES GYMS(GYM_ID),
);
